\begingroup
\chapter*{Introduction}\addcontentsline{toc}{chapter}{Introduction}
\renewcommand{\thesection}{\arabic{section}}

## Objectiver la formation du couple : une entrée par l'homogamie de classe

Trois grandes enquêtes de l'Ined ont marqué la recherche sociologique sur la formation des couples en France. « Le choix du conjoint », dirigée par Alain Girard en 1959, est la première grande étude à exposer les déterminants sociaux des unions matrimoniales. Dans un contexte où le mariage demeure la seule forme de conjugalité socialement acceptée mais où le modèle du « mariage d'amour » est déjà bien installé, les travaux de A. Girard ont montré que la formation des couples ne relevait pas tout à fait du heureux hasard. Plus spécifiquement, l'étude des caractéristiques respectives des deux époux·ses a révélé une forte homogamie des relations : les alliances matrimoniales s'effectuent majoritairement entre personnes qui se ressemblent, en particulier dans leur origine sociale [@girardChoixConjointEnquete1964]. Au delà des « circonstances extérieures » que représentent les distances géographiques et sociales, A. Girard voit dans la régularité de ces unions l'application d'une norme d'homogamie explicite, inculquée de génération en génération au sein de la famille. 

C'est en opposition à de ce dernier postulat que se positionnent Michel Bozon et François Héran lorsqu'ils entreprennent de renouveler les travaux de A. Girard dans les années 1980. Selon eux, l'homogamie n'est pas « le produit concerté d'une anticipation normative agissant à la manière d'une cause finale, mais la résultante agrégée, largement involontaire, d'une multitude de décisions individuelles indépendantes. » [@bozonFormationCoupleTextes2006, p.9-10]. Ce déplacement théorique s'inscrit dans le contexte universitaire de l'époque : alors que Pierre Bourdieu vient de publier *La Distinction, critique sociale du jugement*, où il met au jour le système de goûts et de dégoûts qui structure l'espace social, M. Bozon et F. Héran entendent désenclaver la sociologie du choix du conjoint de la seule sociologie de la famille, pour démontrer ses liens avec « la sociologie de la sociabilité, mais aussi avec la sociologie du jugement et des catégories de perception et, de ce fait, avec la sociologie du recrutement » [@bozonFormationCoupleTextes2006, p.8]. Les deux axes principaux de l'enquête « Formation des couples » de 1983-1984 reflètent cette démarche, le premier s'intéressant à la formation, en amont de la rencontre, de cadres de sociabilité propices à l'homogamie de classe, le second aux « principes de jugement et d'évaluation » des potentiel·les partenaires qui participent, « en silence », au maintien de cette homogamie. De ce deuxième axe d'étude ressortent des dynamiques différentes en fonction du genre : tandis que les hommes accordent principalement de l'importance aux propriétés esthétiques, et plus généralement aux qualités de représentation et de médiation souvent attendues des femmes, l'appréciation des caractéristiques physiques des hommes n'est pour les femmes qu'une étape dans un processus global d'évaluation du statut social d'un éventuel conjoint. Parce que le statut de l'homme est celui qui détermine le statut du couple, les femmes, et d'autant plus les jeunes femmes, doivent porter attention à l'ensemble des propriétés sociales « incorporées » dans le corps du conjoint pressenti.

L'enquête « Étude des parcours individuels et conjugaux » (Épic) menée en 2013-2014 par l'Ined et l'Insee vient compléter ce triptyque. Dans un souci de continuité, elle s'inspire et reprend partiellement les questionnaires des deux enquêtes précédentes, dans leurs thématiques mais aussi dans certains intitulés de question. La mise en regard des trois enquêtes permet par exemple de confirmer l'ouverture progressive des parents aux relations hétérogames tout au long de ces périodes, et une raréfaction des rencontres ayant lieu dans un cadre familial [@bouchet-valatAvisParentsConjoint2021]. Cette dynamique s'accompagne plus généralement d'un affaiblissement de l'homogamie de diplôme, de classe et d'origine sociale [@bouchet-valatEvolutionsHomogamieDiplome2014]. Épic se distingue toutefois de ses prédécesseuses par l'introduction d'un ensemble de problématiques apparues avec les évolutions récentes des formes conjugales et familiales. En 1959 la norme faisait encore coïncider la formation du couple avec le mariage ; dans les années 1980 la cohabitation avant mariage commençait à se banaliser, sans que M. Bozon et F. Héran n'aient toutefois le recul nécessaire pour pouvoir identifier les unions cohabitantes qui n'aboutiraient jamais à un mariage. Trente ans après, les trajectoires conjugales socialement acceptées sont autrement plus diverses : cohabitation avec ou sans mariage, mais aussi multiplication des relations amoureuses à l'échelle de la vie, et donc de périodes de célibat plus ou moins longues et choisies, recompositions familiales, autonomisation croissante de la conjugalité et de la sexualité, plus grande reconnaissance institutionnelle et sociétale de l'homosexualité et de l'homoparentalité. L'enquête a ainsi pour ambition novatrice de retracer des parcours, et élargit pour cela son champ d'étude aux personnes âgées entre 25 et 65 ans en 2014, tandis que l'échantillon interrogé dans « Formation des couples » n'était représentatif que des personnes de moins de 45 ans. Elle est également la première à reconnaître dans son questionnaire la possibilité d'une relation homosexuelle. 

(ref:couple-epic) [@raultEtudierParcoursIndividuels2019, p.13]

\begin{tcolorbox}[float, sharp corners, title=Définition du couple, fonttitle=\bfseries]
La définition de ce qu'est un couple ne relève pas de l'évidence. Elle peut varier dans le temps et d'une personne à une autre, selon les modèles de relation socialement valorisés à l'échelle des groupes sociaux d'appartenance ou de la société dans son ensemble. Dans l'enquête « Choix du conjoint » en 1959, le couple est entendu de manière restreinte comme le résultat d'un mariage hétérosexuel. La définition s'ouvre progressivement avec « Formation des couples » dans les années 1980, où sont interrogés des couples hétérosexuels mariés ou cohabitants. Ce choix ne signifie pas que d'autres formes de relation n'existaient pas à l'époque, mais qu'elles étaient trop minoritaires pour être étudiées dans des enquêtes quantitatives, aux échantillons de répondant·es nécessairement réduits. En 2014, cette diversification des formes conjugales s'est opérée à grande échelle, et les concepteur·ices d'Épic ont opté pour une ouverture complète de la définition du couple en laissant la liberté aux enquêté·es de qualifier leurs relations comme tel :    

\Begin{displayquote}
La difficulté à définir aujourd’hui ce qu’est un couple suggérait plutôt de laisser les personnes interrogées décrire leur vie conjugale et amoureuse dans une acception large et volontairement subjective, en dehors de toutes notions préconçues : pas de limite de durée, pas de restrictions liées à la vie commune, mais simplement les histoires qui font sens à leurs yeux. Ainsi Épic retrace-t-elle l'ensemble des « relations de couple ou relations amoureuses importantes », avec comme précision à l'adresse des enquêtrices et enquêteurs : « on entend par là une relation qui, mariée ou non, pacsée ou non, en vivant ensemble ou non, compte ou a compté dans le passé, même si ça n'est plus le cas aujourd'hui ». (ref:couple-epic)
\End{displayquote}

Par souci de concision et bien que ces expressions puissent renvoyer à des réalités très différentes d'un·e répondant·e à l'autre, nous désignerons comme \textit{couple} les « relations de couple ou relations amoureuses importantes » déclarées dans Épic, et comme \textit{conjoint·es} les membres de ces relations. Ces termes seront également utilisés pour évoquer les relations étudiées dans les enquêtes de 1959 et 1984, bien qu'ils correspondent à des unions alors définies de manière plus stricte.
\end{tcolorbox}



## La persistance d'une hétérogamie d'âge 

Les proximités d'origine et de classe sociale ont été les premières étudiées dans la recherche sur la formation du couple, mais d'autres régularités ont également été mises au jour dans des travaux ultérieurs. La question de l'écart d'âge entre conjoint·es fait partie des plus discutées, et plus spécifiquement l'observation récurrente dans différents pays et à différentes époques que l'homme est en moyenne plus âgé que la femme dans les couples hétérosexuels. Marie Bergström a proposé une synthèse de ces travaux dans un article paru en 2018 : en France, l'écart d'âge a principalement retenu l'attention des démographes et des sociologues, qui ont étudié les évolutions de cet écart et ont notamment montré une réduction de la différence d'âge dans les dernières décennies ; dans la littérature anglo-saxonne, d'autres disciplines se sont emparées du sujet, au premier rang desquelles la sociobiologie et la psychologie évolutionniste qui mettent l'accent sur les supposés déterminants biologiques de l'écart d'âge au sein du couple [@bergstromQuoiEcartAge2018]. Au delà de la dimension fortement naturalisante de ces théories, M. Bergström relève l'usage problématique d'un raisonnement économique en termes de « préférences révélées » : « sur la base d'un écart d'âge moyen entre partenaires - observé au niveau de la *population* - on déduit des préférences *individuelles* ». [@bergstromQuoiEcartAge2018, p.399]

L'orientation spécifique de l'enquête « Formation des couples » vers les goûts et critères de jugement a permis à M. Bozon d'éviter cet écueil théorique lorsqu'il s'est intéressé à la question de l'écart d'âge. L'enquête interroge en effet directement les préférences des répondant·es par rapport à la taille ou l'âge d'un·e éventuel·le conjoint·e : « Accepteriez vous de vivre avec quelqu'un de... ». Si les résultats ont effectivement révélé une préférence généralisée pour les configurations où le conjoint serait plus âgé que la conjointe, ils révèlent surtout une adhésion beaucoup plus marquée à cette norme chez les femmes. Pour l'auteur, cette préférence féminine relève du même « réalisme social » qui poussent les femmes à interpréter l'apparence physique des hommes comme un indicateur de position sociale. Pour les jeunes femmes en début de parcours conjugal notamment, la perspective d'une entrée en couple avec un homme « mature » et déjà installé dans la vie active est en effet un gage de stabilité, ce à quoi ne peut prétendre une relation avec un pair. Les femmes des classes supérieures, moins dépendantes du statut social de leur conjoint, ont la possibilité de prendre plus de distance par rapport à cette norme. Parce que cet écart est un marqueur fort de domination masculine au sein du couple et qu'il apparaît avant tout désiré par les femmes, le sociologue voit dans cette préférence une « domination consentie » [@bozonFormationCoupleTextes2006, chap.3]. 

Le travail de M. Bergström sur le site de rencontre en ligne Meetic s'inscrit dans la même approche sociologique que celle de M. Bozon, mais vient nuancer le constat d'une indifférence masculine généralisée sur cette question. Les données relatives aux comportements des utilisateur·ices du service de rencontre permettent en effet d'aller plus loin que la déclaration des préférences, pour les voir directement à l'œuvre dans un processus de choix. L'autrice souligne alors qu'à des âges de mise en couple plus élevés, ce sont avant tout les préférences des hommes pour des conjointes plus jeunes qui assurent le maintien de l'écart d'âge [@bergstromQuoiEcartAge2018]. Cette étude, inédite de par la nature de ses sources, représente une mise en garde importante sur la manière d'interpréter les goûts déclarés dans des enquêtes par questionnaire comme « Formation des couples » et Épic.

Les travaux de Florence Maillochon sur l'initiation amoureuse et sexuelle des adolescent·es montrent par ailleurs que les préférences d'âge peuvent relever de logiques différentes selon la nature de la relation et sa place dans les trajectoires personnelles. Elle constate notamment que c'est lorsque les relations prennent un caractère sexuel que l'écart d'âge se creuse et que les filles expriment un désir plus marqué d'être avec des garçons plus âgés qu'elles, tandis que les « premiers baisers » s'échangent le plus souvent entre pairs. Les raisons de ce changement sont plurielles : à cette « maturité » recherchée, les filles associent à la fois une éventuelle aisance financière, des qualités esthétiques - « un physique d'homme qui en impose » -, et la sécurité d'avoir ses premiers rapports sexuels avec un partenaire expérimenté [@maillochonAgeAmoursDifference2001]. L'âge est une catégorie sociale qui ne recouvre pas les mêmes significations selon les contextes et les individus, et fait donc l'objet de préférences variables dans le cadre d'une relation amoureuse ou sexuelle.


## Quels autres registres de goûts amoureux ? 

M. Bozon propose, en complément de son étude sur l'écart d'âge, une analyse des goûts relatifs à la taille d'un·e éventuel·le conjoint·e. Les réponses à l'enquête « Formation des couples » montrent que les configurations de couple où la conjointe serait plus grande que le conjoint sont difficilement acceptées, et que les refus sont une nouvelle fois plus fréquents chez les femmes. Pour l'auteur, ces préférences féminines en termes d'écart d'âge et de taille se « ressemblent formellement » et même se « contaminent », et relèvent l'une comme l'autre d'une « domination consentie » par les femmes. L'explication de la norme relative à l'écart de taille est toutefois plus succincte que celle portant sur l'écart d'âge. Elle repose sur l'idée que l'écart de taille représente également un enjeu de statut social pour le couple, puisqu'un homme plus petit que sa conjointe se sentirait « diminué » et diminuerait la position de sa femme en retour [@bozonFormationCoupleTextes2006, p.145].

La question de l'écart de taille a été généralement moins étudiée que celle de l'écart d'âge en France. Dans la littérature anglo-saxonne, elle n'a pas échappé aux théories naturalisantes de la psychologie évolutionniste, dont Nicolas Herpin recense les principales conclusions dans son ouvrage sur l'influence de la taille des hommes sur leur statut social : parce que les femmes accordent le plus d'importance à leur descendance, elles portent aussi le plus d'attention au choix du « partenaire reproducteur », et notamment à la régularité de ses caractéristiques physiques. N. Herpin s'inscrit en partie dans la continuité de ces réflexions, en affirmant que la stature des hommes fonctionne pour les femmes comme le « signal » d'une plus ou moins grande réussite économique et sociale actuelle ou à venir, les hommes grands ayant davantage de chances de réussite en termes d'emploi et de carrière [@herpinPouvoirGrandsInfluence2006]. Mais il propose également des explications alternatives au maintien de la norme de l'écart de taille, notamment l'idée selon laquelle, pour des femmes au statut social déjà bien installé, la recherche du couple « bien assorti » relèverait avant tout d'une exigence esthétique [@herpinTailleHommesSon2003]. Un ouvrage plus récent de Marie Buscatto inverse le point de vue pour s'intéresser aux vécus des femmes « de très grande taille ». Les différents témoignages des femmes enquêtées et les thématiques régulièrement abordées dans les groupes Facebook qu'elles fréquentent montrent la place centrale qu'occupe la question de l'écart de taille dans leur vie amoureuse  [@buscattoTresGrandeTaille2022]. Nous verrons que la position singulière de ces femmes met au jour les liens étroits qui existent entre perception sociale de la taille et fabrique du genre.

De part leur caractère chiffré, les écarts de taille et d'âge au sein du couple sont aisément formulables en termes d'hétérogamie, à la manière dont les premiers travaux sur les unions matrimoniales ont formulé la proximité de classe ou d'origine sociale en termes d'homogamie. Les autres registres de goûts amoureux sont plus difficiles à objectiver, et d'autant plus difficiles à saisir par le biais d'un questionnaire d'enquête. Dans « Formation des couples », M. Bozon et F. Héran étudient les « catégories du jugements amoureux » en interrogeant les enquêté·es sur les qualités qui les ont le plus attiré chez leur conjoint·e en début de relation, les répondant·es étant invité·es à choisir quatre adjectifs dans une liste pré-établies lors d'entretiens préparatoires. Cette approche permet d'enrichir la compréhension des goûts qui interviennent dans la formation du couple, et montre une forte structuration des réponses par le genre et la classe. Les femmes sont par exemple avant tout appréciées pour leurs caractéristiques physiques (« jolie », « séduisante »), et plus généralement pour leurs qualités de représentation (« élégante », « souriante », « simple » pour les femmes de classes populaires). Les hommes sont pour leur part valorisés pour leur statut social et professionnel (« intelligent » dans les classes supérieures, « sérieux » et « travailleur » dans les classes populaires), et pour leurs qualités affectives (« sécurisant », « affectueux ») [@bozonFormationCoupleTextes2006, chap.2].

Avec son travail sur les petites annonces matrimoniales publiées dans le *Le Chasseur Français* à la fin des années 1970, François de Singly propose une approche alternative à l'étude des normes régissant les goûts amoureux. Pour les personnes qui publient ces annonces, et qui sont par conséquent considérées comme les « exclu[e]s du marché matrimonial normal », l'objectif n'est pas de se démarquer mais au contraire de justifier de sa normalité. La présentation de soi relève alors d'une mise en avant des traits anticipés comme valorisés par l'autre sexe, et la formulation des attentes répond avant tout à un raisonnement en termes « d'offre et de demande ». Le sociologue remarque par exemple que les premiers atouts personnels évoqués dans les annonces sont majoritairement liés à la situation professionnelle pour les hommes, à des traits de caractère pour les femmes. La mise en avant de qualités esthétiques s'accompagne par ailleurs chez les femmes d'un intérêt pour les hommes au statut économique élevé, et chez les hommes d'un intérêt pour les femmes physiquement attrayantes [@desinglyManoeuvresSeductionAnalyse1984]. Cette approche a l'avantage de ne pas reposer sur des données collectées dans un cadre contraint et artificiel d'enquête. L'expression des préférences personnelles n'est pas pour autant plus libre dans les petites annonces : leur format répond à des codes stricts, et les attentes formulées sont déterminées par une logique de marché. Mais elle permet de saisir « en pratique » ce que les annonceur·euses considèrent comme les caractéristiques les plus valorisantes et valorisées dans le cadre d'une union matrimoniale. 


## La « matrice hétérosexuelle » : couple et rapports de genre

Comme nous l'avons vu, M. Bozon place les rapports de genre au cœur de sa réflexion sur les préférences d'âge et de taille, la « domination masculine » étant à l'origine de ces normes et de leur persistance. Les réflexions du sociologue sont souvent articulées autour d'un enjeu de « statut social » : dans une société patriarcale, le statut de la femme et du couple dépend de celui de l'homme, et ce déséquilibre explique l'existence de préférences différenciées. Lorsqu'elles considèrent un conjoint potentiel, les femmes font davantage attention à des indices de position sociale chez les hommes, et craignent le renversement des marqueurs de supériorité comme la taille qui produirait chez le conjoint le sentiment d'être socialement « diminué ». M. Bozon aboutit alors au constat paradoxal d'une « persistance des rapports de genre, dont l'inertie survit largement aux transformations des mœurs et aux progrès de l'individualisation » [@bozonFormationCoupleTextes2006, p.14] : comment expliquer, dans une société où les femmes sont de plus en plus considérées socialement et où les normes d'égalité se diffusent, que des marqueurs de domination tels que les préférences d'écart d'âge et de taille persistent ?
 
Nous proposons d'explorer plus avant les raisons de ce paradoxe, en repensant notamment les liens entre couple hétérosexuel et rapports de genre. La relative inertie des dynamiques de domination au sein du couple apparaît en effet moins surprenante lorsque, suivant un courant théorique important de la sociologie du genre, on envisage l'hétérosexualité non pas seulement comme un des lieux où *s'exercent* les rapports de genre, mais avant tout comme un des lieux principaux de *production* du genre. Judith Butler a utilisé l'expression évocatrice de « matrice hétérosexuelle » pour désigner ce régime à travers lequel s'effectue la construction sociale des femmes et des hommes comme des êtres « naturellement » différents et complémentaires [@butlerTroubleDansGenre2006; @clairSociologieGenre2012]. Les travaux d'Isabelle Clair donnent des illustrations très concrètes de cette « fabrique » du genre. Dans un article souvent cité, elle montre comment les figures repoussoirs de la « pute » et du « pédé » sont mobilisées par les jeunes qu'elle enquête comme des rappels à l'ordre du genre. Dans « l'ordre hétérosexuel », appartenir aux groupes des garçons c'est s'éloigner tant que possible de la féminité associée à des pratiques homosexuelles « contre-nature », et être une fille c'est devoir constamment réaffirmer sa vertu face à la suspicion d'une sexualité trop libérée [@clairPedePuteOrdre2012]. 

Ces remarques ne viennent pas disqualifier les interprétations de M.Bozon sur les questions d'écart d'âge et de taille, mais amènent des pistes d'analyse complémentaires ou alternatives. L'auteur explique par exemple que le refus des femmes d'être avec un homme plus petit relève de la crainte que ce dernier se sente « diminué ». On peut argumenter, en s'appuyant notamment sur les travaux de @buscattoTresGrandeTaille2022, que l'enjeu ne s'arrête pas ici à la seule question du statut social du couple, mais touche à l'identité sexuée des deux conjoint·es. Une proximité de taille, ou pire une inversion des rôles qui conduirait à une domination de la femme par la taille, irait à l'encontre de la complémentarité pensée comme naturelle sur laquelle repose l'ordre hétérosexuel. Déroger à la norme de l'écart de taille se rapprocherait alors d'une transgression de genre. Un raisonnement analogue peut s'appliquer à la question de l'âge. Il n'est pas anodin que, comme l'a montré M. Bergström, la préférence des hommes pour les femmes plus jeunes s'affirme avec l'âge. Parce qu'ils ont moins souvent la charge des enfants et parce qu'ils sont davantage enclins à faire « table rase » après une séparation, les hommes se « sentent jeunes » plus longtemps que les femmes [@bergstromQuoiEcartAge2018]. On peut ajouter à cela que, dans le schéma hétérosexuel dominant, la « désirabilité » du corps féminin est beaucoup plus menacée par l'avancée en âge que celle du corps masculin. La représentation des couples dans les fictions audiovisuelles illustre ce traitement différencié des corps : alors que de nombreuses relations font intervenir des jeunes femmes et des hommes excessivement plus âgés qu'elles, les rares personnages féminins de plus de 50 ans sont représentés comme « sorties de la sexualité » [@arbogastLeurAgeSexualite2015]. Concevoir l'hétérosexualité comme un lieu de fabrique du genre conduit ainsi à repenser la place du corps et de sa perception dans la formation des goûts amoureux, au delà d'un rôle de marqueur de classe. 

On peut alors s'interroger sur l'existence de liens entre goûts amoureux et  représentations sur le couple, la sexualité, et leur association. I. Clair montre comment s'installe, dès l'adolescence, une polarisation genrée des discours sur l'expérience amoureuse : « aux garçons la sexualité, aux filles les sentiments » [@clairDivisionGenreeExperience2007, p.146]. Tandis que l'activité sexuelle est valorisée pour elle-même et comme « naturelle » chez les garçons, elle ne saurait être dissociée de sentiments amoureux chez les filles, sous peine de devenir « coupable » en contrevenant à l'injonction de réserve féminine. Une prise de recul par rapport à ces représentations, et finalement aux mécanismes de construction du genre qui les sous-tendent, pourrait-elle s'accompagner d'une remise en question de normes comme celles de l'écart de taille et d'âge au sein du couple ?

## Penser l'imbrication entre genre et classe

Insister sur l'importance du genre et de son lien étroit avec le régime hétérosexuel ne doit pas pour autant conduire à ignorer les enjeux de classe, et plus encore l'imbrication de ces deux systèmes sociaux de hiérarchisation. Cette mise en garde a été formulée par Beverley Skeggs dans son étude de référence sur les femmes de classes populaires anglaises, suivant le constat que la classe constituait un impensé de nombreuses théories féministes de l'époque [@skeggsFormationsClassGender1997, p.6]. Elle montre dans cette étude que la classe joue un rôle central dans le rapport ambigu qu'entretiennent ses enquêtées avec la notion de féminité, cette notion ayant été historiquement définie pour désigner les femmes de classes moyennes précisément en opposition aux femmes des classes populaires. Ces dernières sont alors exposées à l'injonction constante de prouver leur « respectabilité », en s'éloignant notamment le plus possible d'une sexualité à laquelle elles sont, invariablement et plus que les femmes d'autres milieux, associées dans les représentations collectives. Dans ce cadre, l'hétérosexualité et le mariage représentent non seulement une sécurité économique potentielle, mais aussi un marqueur fort de respectabilité [@skeggsFormationsClassGender1997, chap.7].

Ces réflexions ouvrent de nouvelles perspectives pour comprendre la manière dont la classe intervient dans la formation des goûts amoureux. L'enjeu matériel et de « situation » que représente la mise en couple, pour les femmes des classes populaires notamment, ne doit pas être négligé. Mais le caractère variable des injonctions de genre en fonction de la classe ne pourrait-il pas également expliquer l'expression de goûts amoureux différents ? De même qu'il est plus difficile pour les femmes de classes populaires de déroger à la norme de réserve sexuelle, la marge de manœuvre par rapport aux normes d'assortiment telles que l'écart d'âge ou de taille n'est peut-être pas toujours égale. Cette différenciation des injonctions de genre selon la classe n'est d'ailleurs pas propre aux femmes. Le champ émergent des études sur les masculinités, dans le sillage des travaux fondateurs de Raewyn Connell, a montré l'existence d'une multiplicité de façons d'« être un homme », plus ou moins valorisées selon l'époque et le contexte, à une échelle socialement localisée ou à celle de la société [@connellMasculinities2005; @connellFautilRepenserConcept2015]. Bien que les résultats de l'enquête de 1980 aient avant tout pointé vers une plus grande indifférence des hommes dans leurs préférences conjugales, la question d'une éventuelle différenciation des goûts *parmi* les hommes reste pertinente. 


## Biographie conjugale et sexuelle et formation des goûts

La diversification des parcours et des formes conjugales en France dans les dernières décennies complexifie l'étude des relations amoureuses. On imagine facilement que les attentes et les critères de jugement à l'endroit d'un·e potentiel·le conjoint·e ne sont pas exactement les mêmes à 18 ans et à 40 ans, lors d'une première relation et après plusieurs ruptures. On peut également supposer que ces attentes et ces critères varient selon que, à l'échelle d'une vie, on ait connu une seule relation longue ou enchaîné les aventures d'un soir. L'enquête Épic a été conçue pour prendre en compte cette dimension biographique : la personne interrogée était invitée à dénombrer l'ensemble des relations qu'elle jugeait importantes, puis d'en détailler les caractéristiques dans un module de questions récurrent. Plusieurs travaux ont montré l'importance des données de parcours pour expliquer certaines opinions ou choix de vie ultérieurs. 

Arnaud Régnier-Loilier a par exemple constaté que les personnes plus âgées et les femmes ayant de jeunes enfants avaient une plus faible propension à s'engager dans une nouvelle relation cohabitante après une rupture, ce choix pouvant relever de multiples logiques : « attitude de prudence à l'égard d'un nouvel engagement conjugal, manière de concilier de nouvelles aspirations personnelles, préserver ses enfants issus d'une précédente relation et/ou son nouveau partenaire de possibles difficultés liées à la beau-parentalité ». Il remarque également que les femmes ayant connu des relations conflictuelles ou des ruptures tendues sont moins enclines à emménager avec leur nouveau partenaire [@regnier-loilierNouvelleVieCouple2019]. Cette réticence suite à une cohabitation mal vécue se retrouve chez certaines des femmes interrogées par Marie Bergström, Françoise Courtel et Géraldine Vivier dans leur travail sur la vie « hors couple ». Malgré une injonction sociale forte à la remise en couple, le célibat est plébiscité par ces femmes comme une période de liberté et d'autonomie retrouvée, après des expériences conjugales « ancrées dans des rapports de genre et de subordination parfois très marqués, oppressants, voire dépersonnalisants » [@bergstromVieHorsCouple2019].

Un article de Wilfried Rault sur les attitudes *gayfriendly* ouvre également des perspectives intéressantes sur l'importance de la trajectoire personnelle sur la formation des opinions, et notamment sur un effet différencié des biographies sexuelles selon le sexe : alors qu'un nombre important de partenaires sexuelles s'accorde, chez les hommes, avec « un modèle de virilité dominant qui se combine à un rejet de l'homosexualité », il représente au contraire pour les femmes une rupture « avec des attentes sociales qui les enjoignent à une sexualité conjugale et procréative », et s'accompagne d'attitudes plus favorables à l'homosexualité [@raultAttitudesGayfriendlyFrance2016]. 

## Une « moyennisation » des goûts amoureux ?

L'étonnement de M. Bozon face à la persistance de marqueurs de domination masculine dans les goûts amoureux amène à s'interroger sur les conditions de réception des discours sur les inégalités de genre au sein du couple, de plus en plus présents dans le débat public depuis les années 1980. Que ce soit dans les médias d'information ou dans les œuvres de fiction, le modèle du couple égalitaire se diffuse dans tout l'espace social. Il repose sur une éthique générale du partage : des tâches domestiques, de la charge parentale, mais aussi de plus en plus d'un plaisir mutuel trouvé dans la sexualité [@bozonSociologieSexualite2018]. Il est alors possible d'imaginer qu'une forme d'indifférence face aux questions d'écart d'âge ou de taille entre conjoint·es, ou qu'une attention égale aux caractéristiques esthétiques chez les femmes et chez les hommes, viennent compléter cette remise en cause de marqueurs traditionnels de la domination masculine au sein du couple. On peut se demander dans quelle mesure la diffusion d'idées autrefois réservées à des cercles féministes restreints pourrait avoir entraîné une homogénéisation des représentations et des goûts amoureux entre les sexes.

En 1984, M. Bozon et F. Héran ont également mis l'accent sur l'existence de goûts amoureux ancrés dans des considérations de classe, ou du moins de « statut » social. Ils notent ainsi que les jeunes femmes de classes populaires sont davantage attachées à la norme de l'écart d'âge par « réalisme social », ayant conscience que leur statut allait principalement reposer sur celui de leur futur conjoint [@bozonFormationCoupleTextes2006, chap. 3]. L'autonomie matérielle et la considération sociale accordée aux femmes a augmenté depuis les années 1980, et la première union est de plus en plus rarement la seule dans le parcours conjugal. Ces évolutions ont pu participer à réduire la différence de goûts selon la classe sociale chez les femmes. Les deux sociologues ont par ailleurs relevé une influence nette de la classe sur les critères de jugement amoureux : les hommes de classes supérieures sont valorisés pour leur intelligence et leur culture, ceux des classes populaires pour leur travail et leur courage, les femmes des classes supérieures sont appréciées pour leur spontanéité, et celles des classes populaires pour leur simplicité et leur soin [@bozonFormationCoupleTextes2006, chap. 2]. Alors que l'homogamie de classe semble décliner à l'échelle de la société [@bouchet-valatEvolutionsHomogamieDiplome2014], et à la manière d'Henri Mendras qui avait vu dans l'essor des médias de masse le support d'une « moyennisation » des goûts et pratiques culturelles des Français·es [@mendrasSecondeRevolutionFrancaise1988], on peut faire l'hypothèse d'un affaiblissement de cette structuration des goûts amoureux selon la classe. 



## Étudier les goûts amoureux hétérosexuels à partir de l'enquête Épic

\begin{tcolorbox}[float, sharp corners, title=L'enquête Épic, fonttitle=\bfseries]

L'enquête \textit{Étude des parcours individuels et conjugaux} (Épic) a été réalisée par l'Ined et l'Insee entre 2013 et 2014, auprès de 7 825 personnes âgées entre 25 et 65 ans et résidant en France métropolitaine en logement ordinaire. 91\% des entretiens ont été réalisés au domicile des enquêté·es, les 9\% restant ayant été passés par téléphone pour accommoder les disponibilités. Une variable de pondération a été construite par les concepteur·ices de l'enquête pour corriger la non-réponse totale et assurer la représentativité de l'échantillon.\\

Le questionnaire d'Épic s'articule en plusieurs temps. Une première partie porte sur les caractéristiques sociodémographiques de l'enquêté·e et de son entourage familial. L'enquêté·e est ensuite invité·e à déclarer le nombre de « relations de couple ou relations amoureuses importantes » qu'iel a connues. Un module de questions détaillé est alors répété pour chacune de ces relations : date des différents évènements qui ont pu la jalonner (début, premiers rapports sexuels, mariage, pacs, séparation, divorce, etc.), lieu de la rencontre et temporalité de la mise en couple, caractéristiques sociodémographiques du ou de la conjoint·e, premières impressions, etc. Des informations supplémentaires sont également collectées à propos de la dernière séparation et de la relation en cours, pour les personnes concernées par ces situations. Trois modules originaux clôturent le questionnaire : le premier s'adresse aux personnes qui ne sont pas en couple au moment de l'enquête et s'intéresse aux ressentis et expériences liées à cette situation ; le second porte sur l'utilisation des sites de rencontres ; le dernier interroge les « opinions et représentations », religieuses et politiques d'abord, puis plus spécifiquement celles sur le couple.\\

Afin de limiter la gêne qu'elles auraient pu susciter dans le cadre d'un entretien en face-à-face, les questions relatives aux pratiques sexuelles (âge aux premiers rapports, nombre de partenaires sexuel·les) ont fait l'objet d'un protocole de collecte particulier : l'enquêté·e y répondait directement sur le micro-ordinateur de l'enquêteur·ice, cet·te dernier·ère n'ayant pas accès aux réponses enregistrées.

\end{tcolorbox}

Contrairement à ses prédécesseuses, l'enquête Épic à été conçue pour prendre en compte les relations homosexuelles. De fait, l'étude d'une éventuelle différenciation des goûts amoureux en fonction de l'orientation sexuelle ou de l'expérience de relations avec des personnes de même sexe ou de sexe différent aurait constitué un apport important, mais cette comparaison se heurte à deux écueils méthodologiques. En premier lieu, le questionnaire ne permet pas à l'enquêté·e de s'auto-identifier comme hétérosexuel·le, homosexuel·le, bisexuel·le, ou par un autre intitulé de son choix. L'orientation sexuelle doit alors être approchée à partir des relations amoureuses ou sexuelles déclarées, et aucune information n'est disponible pour les personnes n'ayant pas connu ce type de relations. Un problème adjacent réside dans la binarité des catégories de sexe proposées dans le questionnaire : tandis que les enquêté·es ne pouvaient être identifié·es que comme des femmes ou des hommes, le choix d'une modalité « ne sait pas » était possible pour désigner la·e conjoint·e dans chaque relation importante. Cette modalité n'a été choisie que 8 fois sur les 14 699 relations recensées et ces choix relèvent peut-être d'une simple erreur de saisie, mais ils rappellent le caractère restrictif d'une conception du genre se limitant à deux catégories de sexe, et posent accessoirement problème dans l'identification d'une relation homosexuelle ou hétérosexuelle à partir du questionnaire. 

La deuxième difficulté est liée au nombre restreint de personnes ayant déclaré des relations homosexuelles dans l'enquête [@raultHomosexualiteBisexualiteApports2019], qui limite fortement les possibilités de croisement et la qualité des traitements statistiques. La faiblesse de ces effectifs nous amène à restreindre notre étude aux répondant·es hétérosexuel·les, ou du moins supposé·es comme tel·les : nous écartons de l'échantillon toutes les personnes ayant déclaré au moins une relation importante avec une personne de même sexe, ainsi que l'ensemble des personne ayant eu au moins un·e conjoint·e dont le sexe n'est pas connu. Partant d'un effectif de départ de 7 825 répondant·es, on réduit ainsi l'échantillon à 7 704 personnes. Cette sélection est loin d'être optimale, puisqu'elle présume notamment l'hétérosexualité des 347 personnes n'ayant déclaré aucune relation de couple importante, et qu'elle ne tient pas compte d'éventuelles expériences sexuelles avec un·e partenaire de même sexe. Le peu de personnes concernées par ces incertitudes permet cependant de relativiser la perte de représentativité engendrée par ces choix.

Épic, comme « Formation des couples » avant elle, permet d'étudier les goûts amoureux selon deux approches différentes. La première consiste à interroger des préférences par le bais d'une relation fictive : « Accepteriez-vous d'être avec quelqu'un·e de... » plus grand·e, plus petit·e, plus âgé·e, plus jeune. Les questions sur la taille et l'âge d'un·e éventuel·le conjoint·e sont communes aux deux enquêtes, mais Épic introduit deux nouvelles dimensions en mesurant la tolérance aux écarts de diplôme et aux divergences d'opinions politiques. Ces questions ont l'avantage d'interroger directement des normes désormais bien connues des sociologues, et de permettre une mise en regard aisée des réponses avec les caractéristiques individuelles des enquêté·es. Elles imposent cependant aux répondant·es de s'exprimer sur des préférences qui n'ont pas nécessairement d'intérêt à leurs yeux, dans un cadre fictif où il peut être difficile de se projeter lorsqu'on n'est pas familier de ce type d'exercice. 

Pour tenter de contourner ces difficultés, une deuxième approche consiste à s'intéresser aux qualités qui ont effectivement plu chez un ou une conjoint·e au moment de la formation du couple. Dans Épic, cette approche se traduit par une question ouverte posée pour chaque relation importante déclarée par l'enquêté·e : « Parlons de vos premières impressions concernant [prénom du/de la conjoint·e]. Qu'est-ce qui vous a plu chez lui/elle ? ». Comme évoqué précédemment, une question analogue était posée dans l'enquête de 1984, mais les répondant·es devaient choisir quatre qualités parmi une liste prédéfinie d'adjectifs. Au delà de la confrontation intéressante de ces deux méthodologies de collecte, une telle question permet de mettre en regard les goûts interrogés par le biais de relations fictives et les qualités valorisées dans le cadre de relations effectivement vécues. Les critères de jugement ne sont en effet plus limités aux questions d'âge, de taille, de diplôme ou d'opinions politiques, l'enquêté·e étant libre de définir les registres les plus importants à ses yeux dans l'appréciation d'un·e conjoint·e. 

Un des enjeux de notre travail sera d'évaluer les apports et les limites respectives de ces deux approches, et de tenter d'expliquer d'éventuelles difficultés à répondre aux différentes questions mobilisées selon leur format. Qu'elles portent sur des relations fictives ou des relations vécues, les préférences recueillies par l'intermédiaire d'un questionnaire restent par ailleurs de l'ordre du discours, et doivent donc être analysées en gardant à l'esprit la possibilité d'une incohérence entre goûts déclarés et goûts effectifs.

En s'appuyant ainsi sur les données de l'enquête Épic, ce mémoire cherche à réactualiser, trente ans après l'enquête « Formation du couple », le portrait du conjoint ou de la conjointe idéal·e, ou du moins les qualités particulièrement valorisées ou rédhibitoires dans le cadre d'une relation amoureuse hétérosexuelle. Il emprunte à M. Bozon une approche multidimensionnelle des goûts, qui vise à faire apparaître des logiques communes derrière la formation de préférences *a priori* indépendantes telle que celles pour l'âge, la taille, le niveau de diplôme ou les opinions politiques d'un·e conjoint·e. Mais il vise également à mettre au jour la multiplicité des espaces sociaux susceptibles d'expliquer ces goûts. Un des regrets de M. Bozon et F. Héran à la suite de l'enquête « Formation des couples » a en effet été de ne pas avoir pu mobiliser les méthodes d'analyse multivariée pour enrichir leur compréhension des préférences amoureuses [@bozonFormationCoupleTextes2006]. Nous tirerons parti de ces méthodes pour tenter d'isoler les éventuels liens entre les goûts amoureux et les caractéristiques sociodémographiques et biographiques présentées précédemment.

Nous commencerons par étudier ces goûts amoureux selon les axes traditionnels du genre et de la classe, puis nous enrichirons cette analyse dans un deuxième chapitre par l'introduction des enjeux de représentations sur le couple et de parcours individuel. Un dernier chapitre complétera ces réflexions par l'étude des caractéristiques effectivement valorisées par les enquêté·es dans les relations qu'elles et ils ont vécues.

\endgroup
